### ISSUE TITLE
Add Compass lock button

### ISSUE THREAD

**Issue by jidanni** [ShowMeHills/ShowMeHills#30]
Okay I have finally figured out how we can get this app to work properly. I suppose most cell phones compasses do not work when the phone is held up as in taking a picture. The compasses Were Meant to work when the phone is lying flat on a desk. Therefore the procedure should be to First hold the phone flat on a desk until the compass stabilizes then push a lock button. So the interface should add some kind of a lock button. Then the user should slowly raise the phone so he can see the mountains through the camera and then he will thus have the names appear in front of the correct mountains. I apologize for the punctuation in this bug report. I am using Google Talk input.

**Comment by jidanni** [comment]
Or maybe add an auto lock option. When the user races the phone from a flat orientation more than 10 degrees the auto lock will kick in, and freeze the compass reading.

**Comment by jidanni** [comment]
Raises.

**Comment by jidanni** [comment]
On the other hand the Sky Map application has no problem at all, with gyroscopes enabled or disabled. Well all I know is show me Hills only shows the correct azimuth on the screen when phone is flat on a desk. Therefore there should be still a lock button or option available on for example  Zenfone 3 on Android 7.0.

**Comment by jidanni** [comment]
The all-in-one offline maps application also has problems with the compass when the phone is raised up as in to take a picture.

**Comment by nikcain** [comment]
Clearly this is not the case as this and many other apps would not work. 
The mechanism for determining orientation of the phone in relation to compass direction is completely available in the android OS, but the app has to be developed to recognise it in orientations other than one plane. Many simple compass apps don't do this as they would only be operated flat (on a table say). Showmehills has been developed to recognise the compass bearing when in the vertical.

If you're having trouble with the compass bearing I recommend trying the various techniques to calibrate your compass - Google it or look on YouTube, there are lots of ways. The calibration is at the device level and has nothing to do with showmehills code.

**Comment by nikcain** [comment]
https://support.google.com/maps/answer/6145351

**Comment by jidanni** [comment]
OK I'll try that. In the meantime there still could be certain phones that would benefit from compass lock button, https://github.com/cgeo/cgeo/issues/5889 , or at least to stop all the jitter...

**Comment by jidanni** [comment]
Chartcross GPS test  app gives same result. When held flat the compass is fine. When held up the compass is not fine. I did many figure 8 s, and confirmed the beam is narrow just like on the Google help page. You will just have to kindly take my word for it that there are some cell phones whose compasses give accurate readings when the phone is held flat.

**Comment by jidanni** [comment]
Only when the cellphone is held flat.

**Comment by nikcain** [comment]
Does the compass point in the wrong direction or is very jittery?

If it's jittery then there's a smoothing setting in the preferences. Otherwise I can see that a lock button would work, but it would be very complicated to explain in the help - I doubt many people would get it (or have the patience to discover the feature).

**Comment by jidanni** [comment]
it was showing the wrong  azimuth with no regular pattern as to what the correct azimuth should be. Anyway, never mind that. It's doing better today. However you still need a general lock screen button so the user can take what he sees, Frozen, into a shady area and examine what's on the screen. So okay we don't need a lock Compass button you just need a General freeze screen button. You might say well just take a snapshot. However that's a much bigger hassle and you have to clean it up later. So I propose  1-tap of this new button will freeze the screen. A second tap will release the freeze.

**Comment by jidanni** [comment]
Wait, how about a super duper button. It could one freeze the compass. Two freeze the picture. Or three freeze both!

**Comment by jidanni** [comment]
How to implement the super duper button is beyond my knowledge.

**Comment by jidanni** [comment]
By freeze the compass I mean freeze all the mountain notations flying around, so you might say freeze the captions.

**Comment by nikcain** [comment]
Actually there's been a similar request before to be able to drag the markers (so starting the drag 'disconnects' the compass). It was a tricky one to implement but a good idea...

**Comment by jidanni** [comment]
Yes, as it seems there would be little chance everything all works out
perfectly in the field... and even if it did on a sunny day one would
probably need to go back into the shade of one's car to review what the
screen shows.

Actually you would need two independent toggle buttons. One to toggle
freezing the titles (mountain names), one to toggle freezing the
image. That way the user could independently operate them as he
pleases. Also maybe toss in the ability to toggle on/off the titles
completely.

And like you mentioned, once frozen perhaps even allow the user to grab
them (hmmm, titles, or image) and move them around as a block...

**Comment by jidanni** [comment]
http://www.offline-maps.net/en/help/orientation says hold phone horizontally.

**Comment by nikcain** [comment]
The Android OS doesn't provide a nice simple means to say 'phone is facing 40 degrees NE'. Instead it gives a sophisticated mechanism that takes into account all the sensors (https://developer.android.com/guide/topics/sensors/sensors_overview.html). It takes a fair bit of transformation and matrix maths to convert those sensor values into a plain simple compass reading (combining the magnetic sensor with the XYZ phone orientation). Doing this in one dimension isn't too much trouble (i.e. phone lying flat), but once you mix in a vertical component it gets difficult (is the phone rotated, which way is it rotated etc).
It took a long time to get it right in showmehills, and I'm not surprised that not many apps attempt it (why would they when most compasses are used flat). It is correct (with one exception - I noticed the map overlay view is allowing a portrait format which shouldn't be happening as the compass wasn't calculated for that orientation).

**Comment by jidanni** [comment]
Maybe you could add an option: just try with API version:
[ ]15 (Android version ...)
[ ]16 (Android version ...)
[ ]17 etc.
so the user could see if app works better for him using some older
simpler standard. Or just have an option to 'try simpler calculations'
(like the other apps you mentioned, 'at the cost of ...', 'just in case
... for your phone'.
